version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: inkwell_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/inkwell_dev
      - SECRET_KEY=dev-secret-key-not-for-production
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:
