[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "inkwell.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = [
    "--cov=blog",
    "--cov=inkwell", 
    "--cov-report=html",
    "--cov-report=term-missing",
    "--strict-markers",
    "--disable-warnings",
    "-v"
]
testpaths = ["tests", "blog/tests"]
markers = [
    "unit: Unit tests",
    "integration: Integration tests", 
    "slow: Slow running tests"
]
